### ISSUE TITLE
Compilation issue on Elixir 1.7

### ISSUE THREAD

**Issue by safwanolaimat** [sheharyarn/que#9]
> == Compilation error in file lib/exquisite.ex ==
** (CompileError) lib/exquisite.ex:103: __CALLER__ is available only inside defmacro and defmacrop
   lib/exquisite.ex:103: (module)
could not compile dependency :exquisite, "mix compile" failed. You can recompile this dependency with "mix deps.compile exquisite", update it with "mix deps.update exquisite" or clean it with "mix deps.clean exquisite"

Elixir Version = Elixir v1.7.0-dev

**Comment by sheharyarn** [comment]
Hi @safwanolaimat. Thank you for taking the time to report this issue. I'm well aware of the compilation problems on Elixir 1.7 (related to #7).

The problem lies with the [Exquisite](https://github.com/meh/exquisite) dependency, which itself is a dependency of [Amnesia](https://github.com/meh/amnesia/). I'm currently in the process of moving away from both of them, by implementing a custom wrapper for Erlang's Mnesia.

Be on the lookout for `v0.6` of the package, which should resolve all compilation problems. Thank you again!

**Comment by safwanolaimat** [comment]
Thanks

**Comment by sheharyarn** [comment]
I've published `v0.7` of that package. Que now uses the [Memento](https://github.com/sheharyarn/memento) library instead of Amnesia, completely side-stepping compilation and macro issues caused by it.

Please let me know if you have any other issues.
